-- Migration: Add user_id to messages and update RLS policies for authenticated users
-- Executed at: 2026-04-10T07:49:43Z
-- Generated by Could Code

ALTER TABLE messages ADD COLUMN user_id UUID REFERENCES auth.users(id);

-- Drop the anonymous policies
DROP POLICY IF EXISTS "Allow anonymous read access" ON messages;
DROP POLICY IF EXISTS "Allow anonymous insert access" ON messages;

-- Create policies for authenticated users
CREATE POLICY "Allow authenticated read access" ON messages FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert access" ON messages FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
