-- Migration: Create messages table for chat app
-- Executed at: 2026-04-10T07:46:39Z
-- Generated by Could Code

CREATE TABLE messages (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Create policies for anonymous access (for simplicity in this basic chat app)
CREATE POLICY "Allow anonymous read access" ON messages FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert access" ON messages FOR INSERT WITH CHECK (true);

-- Enable real-time for the messages table
ALTER PUBLICATION supabase_realtime ADD TABLE messages;
