// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: vizspsnmuoicagpgouti

class SupabaseConfig {
  static const String supabaseUrl = 'https://vizspsnmuoicagpgouti.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpenNwc25tdW9pY2FncGdvdXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3MTkzNTEsImV4cCI6MjA5MTI5NTM1MX0.lb1O1pbRntJDjvOdltTD16WELQA00nwmh3xy44ajlVE';
}
